language: node_js

node_js:
    - '6'

env:
    global:
        - GIT_REPO="https://$GH_TOKEN@github.com/argoroots/polska.git"
        - GIT_USER="Argo Roots"
        - GIT_EMAIL="argo@roots.ee"

        - BUILD_DIR=./build
        - SOURCE_DIR=./source
        - OUT_DIR=./tmp_source

        - ENTU_URL=https://poola.entu.ee
        - E_DEF=profile
        - TEMPLATE=${SOURCE_DIR}/list-index.jade
        - DATA_LIST=${OUT_DIR}/entities.yaml

# Get GitHub token (public_repo) from https://github.com/settings/tokens/new and set it as GH_TOKEN env parameter
before_script:
    - SOURCE_COMMIT=$(git rev-parse --short HEAD)

    - npm install entu-cms

    - mkdir ${OUT_DIR}
    - mkdir ${BUILD_DIR}

    - cp -r ${SOURCE_DIR}/* ${OUT_DIR}

    - cd ${BUILD_DIR}
    - git init
    - git config user.name ${GIT_USER}
    - git config user.email ${GIT_USER}
    - git remote add upstream ${GIT_REPO}
    - git fetch upstream
    - git reset upstream/gh-pages
    - touch .
    - cd ..

script:
    - ./node_modules/entu-cms/helpers/entu2yaml.js
    - ./node_modules/entu-cms/build.js ./entu-cms.yaml

after_success:
    - cd ${BUILD_DIR}
    - git add -A .
    - git commit -m "Rebuild gh-pages at commit ${SOURCE_COMMIT}"
    - git push -q upstream HEAD:gh-pages
