language: node_js

node_js:
    - '6'

env:
    - ENTU_URL=https://poola.entu.ee OUT_DIR=./tmp_source E_DEF=profile TEMPLATE=./source/list-index.jade DATA_LIST=./tmp_source/entities.yaml

# Get GitHub token (public_repo) from https://github.com/settings/tokens/new and set it as GH_TOKEN env parameter
before_script:
    - npm install entu-cms
    - mkdir ./tmp_source
    - mkdir ./build
    - cp -r ./source/* ./tmp_source
    - cd build
    - git init
    - git config user.name "Argo Roots"
    - git config user.email "argo@roots.ee"
    - git remote add upstream "https://$GH_TOKEN@github.com/argoroots/polska.git"
    - git fetch upstream
    - git reset upstream/gh-pages
    - touch .
    - cd ..

script:
    - ./node_modules/entu-cms/helpers/entu2yaml.js
    - ./node_modules/entu-cms/build.js ./entu-cms.yaml

after_success:
    - cd build
    - git add -A .
    - git commit -m "Rebuild gh-pages at commit ${SOURCE_COMMIT}"
    - git push -q upstream HEAD:gh-pages
