language: node_js

node_js:
    - '6'

env:
    - ENTU_URL=https://poola.entu.ee OUT_DIR=./tmp E_DEF=profile TEMPLATE=./source/list-index.jade DATA_LIST=./tmp/entities.yaml

before_script:
    - npm install entu-cms
    - mkdir ./tmp
    - cp -r ./source/* ./tmp

script:
    - ./node_modules/entu-cms/helpers/entu2yaml.js
    - ./node_modules/entu-cms/build.js ./config.yaml

after_success:
    - SOURCE_COMMIT=$(git rev-parse --short HEAD)
    - cd docs
    - git init
    - git config user.name "Argo Roots"
    - git config user.email "argo@roots.ee"
    - git remote add upstream "https://$GH_TOKEN@github.com/argoroots/polska.git"
    - git fetch upstream
    - git reset upstream/gh-pages
    - touch .
    - git add -A .
    - git commit -m "Rebuild gh-pages at commit ${SOURCE_COMMIT}"
    - git push -q upstream HEAD:gh-pages
