locales:
source: ./source
build: ./docs
assets: ./assets

protectedFromCleanup:
    - assets
    - index.html

jade:
    basedir: ./source/_templates
    pretty: false
markdown:
    html: true
    breaks: true
stylus:
    pretty: false
javascript:
    pretty: false

server:
    port: 4000
    assets: /assets/

cleanup:
    delete: true

dev:
    aliases: true
    paths:
